/**:
  ros__parameters:
    device:
      mirte:
        type: pcb
        version: 0.8
        board: pico
        max_frequency: 10
    encoder:
      main:
        name: main
        device: mirte
        pins:
          pin: GP10          # pin needs interrupt support
        ticks_per_wheel: 20
    modules:
      movement:
        device: mirte
        type: BNO055
        connector: I2C1
      motorserrvocontroller:
        device: mirte
        type: PCA9685
        addr: 0x40
        connector: I2C1
        frequency: 50
        servos: # TODO: No Idea which motor configuration is correct. Test
          gas:
            pin: 1 #0
          stuur:
            pin: 0 #1
 